import { StyleSheet, Dimensions } from 'react-native';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F1F5F9', zIndex: 51},
  header: {
    marginTop: 10,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    zIndex: 51,
  },
  main: { flex: 1 },
  footer: {
    height: 70,
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#eee'
  },
  tab: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  activeTab: { backgroundColor: '#f0f0f0', borderTopWidth: 2, borderTopColor: 'blue' },
  tabText: { fontWeight: 'bold', fontSize: 12 },
  scoreContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: '100%',
    marginRight: 5
  },
  icon: {
    fontSize: 40,
    flex: 1
  },
  pullIcon: { 
    color: '#94A3B8', 
    fontSize: 18, 
    fontWeight: 'bold',
    zIndex: 50,
  },
  scoreShade: {
    position: 'absolute',
    top: 34,
    left: 0, 
    right: 0,
    height: 20,
    backgroundColor: '#d9e7fd',
    zIndex: 50,
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    elevation: 1,
    width: '100%',
  },
  contentPlaceholder: {
    position: 'absolute',
    flex: 1, 
    justifyContent: 'center',
    alignItems: 'center', 
    width: '101%',
    overflow: 'hidden',
    top: 60,
    height: "auto",
    zIndex: 50,
  },
  invisibleShade: {
    position: 'absolute',
    height: 2000,
    width: 2000,
    left: -500,
    right: 0,
    top: -500,
    zIndex: 49,
    backgroundColor: 'rgba(0,0,0,0)',
  },
  moodMeter: { 
    top: 0,
    alignItems:'center',
    transform: [{ translateY: -230 }],
    justifyContent: 'space-evenly',
    backgroundColor: '#F8FAFC',
    height: 374,
    width: '99%',
    elevation: 1,
  },
  todoWrapper: {
   flex: 1,
  },
  inputContainer: {
    flexDirection: 'row',
    marginTop: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderColor: '#ddd',
    paddingHorizontal: 20,
  },
  input: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 12,
    fontSize: 16,
    color: '#1E293B',
    elevation: 2,
  },
  addButton: {
    backgroundColor: '#d9e7fd',
    marginLeft: 10,
    borderRadius: 12,
    width: 50,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  addButtonText: { 
    color: '#FFF', 
    fontSize: 24, 
    fontWeight: 'bold',
    marginBottom: 3,
    textAlign: 'center',
  },
  
  todoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 15,
    elevation: 1,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#3B82F6',
    marginLeft: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checked: { backgroundColor: '#3B82F6' },
  checkMark: { color: '#FFF', fontSize: 14, fontWeight: 'bold' },
  todoText: { flex: 1, fontSize: 16, color: '#1E293B', margin: 15},
  completedText: { textDecorationLine: 'line-through', color: '#94A3B8' },
  deleteIcon: { fontSize: 20, marginLeft: 10 },
  deleteBack: {
    backgroundColor: '#EF4444',
    justifyContent: 'center',
    alignItems: 'flex-start',
    height: '100%',
    paddingRight: 200,
    paddingLeft: 10,
    borderBottomLeftRadius: 15,
    borderTopLeftRadius: 15,
  },
  containerColumn: { flex: 1, flexDirection: 'column', justifyContent: 'center', alignItems: 'center'},
  baseText: {
    color: '#666',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 15,
    
  },
  linkText: {
    color: '#007AFF',
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  authButton: {
    justifyContent: 'center',
    backgroundColor: '#d9e7fd',
    borderRadius: 12,
    padding: 12,
    marginTop: 10,
    elevation: 2
  },
  authButtonText: {
    color: '#3B82F6',
    fontSize: 20, 
    fontWeight: 'bold',
  },
  authInput: {
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#1A202C',
    width: '100%',
  },
  surfaceAuth: {
    width: '75%',  
    marginBottom: 10,
    borderRadius: 12,
    backgroundColor: 'none',
  },
  progressContainer: { marginBottom: 20 },
  progressText: { fontSize: 18, fontWeight: 'bold', marginBottom: 8 },
  progressBarBg: { height: 10, backgroundColor: '#E0E7FF', borderRadius: 5 },
  progressBarFill: { height: 10, backgroundColor: '#3B82F6', borderRadius: 5 },
  inputWrapper: { flexDirection: 'row', marginBottom: 20 },
  item: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    backgroundColor: '#fff', 
    padding: 15, 
    borderRadius: 12, 
    marginBottom: 10,
    elevation: 2 
  },
  itemCompleted: { opacity: 0.6 },
  itemText: { marginLeft: 10, fontSize: 16 },
  textCompleted: { textDecorationLine: 'line-through' }
});