@echo off
echo Starting Backend Server...
start cmd /k "cd backend && .\venv\Scripts\python.exe -m uvicorn main:socket_app --host 0.0.0.0 --port 8000 --reload"

echo Starting Expo Web Server...
start cmd /k "cd frontend && npx expo start"

echo Waiting for Expo server to spin up (6 seconds)...
timeout /t 6 /nobreak > nul

echo Starting Electron Desktop App...
cd desktop
npm run start:dev
