import { StyleSheet, Platform } from 'react-native';

export const getStyles = (theme) => StyleSheet.create({
  header: {
    marginTop: theme.spacing.smd,
    height: theme.sizes.headerHeight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: theme.spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border.light,
    zIndex: 51,
  },
  scoreContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: '100%',
    marginRight: theme.spacing.xs,
    zIndex: 10,
  },
  icon: {
    fontSize: 40,
    flex: 1,
  },
  pullIcon: {
    color: theme.colors.text.secondary,
    fontSize: 18,
    fontWeight: 'bold',
    zIndex: 50,
  },
  headerButton: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: theme.colors.icon.bg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerButtonActive: {
    backgroundColor: theme.colors.icon.bgActive,
  },
  scoreShade: {
    position: 'absolute',
    top: 34,
    left: 0,
    right: 0,
    height: 20,
    backgroundColor: theme.colors.primaryLight,
    zIndex: 50,
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    borderBottomLeftRadius: theme.radius.md,
    borderBottomRightRadius: theme.radius.md,
    elevation: 1,
    width: '100%',
  },
  contentPlaceholder: {
    position: 'absolute',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '101%',
    overflow: 'hidden',
    top: 60,
    height: 'auto',
    zIndex: 50,
  },
  invisibleShade: {
    position: Platform.OS === 'web' ? 'fixed' : 'absolute',
    top: Platform.OS === 'web' ? 0 : -120,
    left: Platform.OS === 'web' ? 0 : -100,
    right: Platform.OS === 'web' ? 0 : -110,
    bottom: Platform.OS === 'web' ? 0 : -1000,
    zIndex: 49,
    backgroundColor: 'rgba(0,0,0,0.1)',
  },
  moodMeter: {
    top: 0,
    alignItems: 'center',
    transform: [{ translateY: -230 }],
    justifyContent: 'space-evenly',
    backgroundColor: theme.colors.surface,
    height: theme.sizes.moodMeterHeight,
    width: '99%',
    elevation: 1,
  },
  webTvSettings: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.radius.lg,
    height: 50,
    flex: 1,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  webDailySettings: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.radius.lg,
    height: 50,
    flex: 1,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  webSettingsText: {
    fontSize: 16,
    color: theme.colors.text.secondary,
    fontWeight: '500',
  },
  keyboardSuggestionCheckbox: {
    width: 26,
    height: 26,
    borderRadius: theme.radius.xs,
    borderWidth: 2,
    borderColor: theme.colors.border.default,
    alignItems: 'center',
    justifyContent: 'center',
  },
  keyboardSuggestionCheckboxChecked: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  episodeInput: {
    width: 50,
    height: 34,
    borderRadius: theme.radius.xs,
    borderWidth: 1.5,
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.background,
    color: theme.colors.text.primary,
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 16,
    padding: 0,
  },
  divider: {
    width: 1,
    height: 24,
    backgroundColor: theme.colors.border.light,
  },
  weekdayBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  weekdayBtnSelected: {
    backgroundColor: theme.colors.background,
    borderColor: theme.colors.primary,
  },
  weekdayBtnText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: theme.colors.text.secondary,
  },
  weekdayBtnTextSelected: {
    color: theme.colors.primary,
  },
  progressValueText: {
    fontSize: 18,
    fontWeight: 'bold',
    marginHorizontal: 6,
    color: theme.colors.text.primary,
    minWidth: 16,
    textAlign: 'center',
  },
  webHeader: {
    paddingHorizontal: 12,
    justifyContent: 'space-between',
  },
  webHeaderLeft: {
    flex: 1,
    marginHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  webHeaderCenter: {
    flex: 1,
    marginHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    gap: theme.spacing.sm,
  },
  webHeaderRight: {
    flex: 1,
    marginHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
});
