import { StyleSheet } from 'react-native';
import { theme } from '../theme/theme';

export const styles = StyleSheet.create({
  header: {
    marginTop: theme.spacing.smd,
    height: theme.sizes.headerHeight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: theme.spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border.light,
    zIndex: 51,
  },
  scoreContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: '100%',
    marginRight: theme.spacing.xs,
    zIndex: 10,
  },
  icon: {
    fontSize: 40,
    flex: 1,
  },
  pullIcon: {
    color: theme.colors.text.secondary,
    fontSize: 18,
    fontWeight: 'bold',
    zIndex: 50,
  },
  scoreShade: {
    position: 'absolute',
    top: 34,
    left: 0,
    right: 0,
    height: 20,
    backgroundColor: theme.colors.primaryLight,
    zIndex: 50,
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    borderBottomLeftRadius: theme.radius.md,
    borderBottomRightRadius: theme.radius.md,
    elevation: 1,
    width: '100%',
  },
  contentPlaceholder: {
    position: 'absolute',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '101%',
    overflow: 'hidden',
    top: 60,
    height: 'auto',
    zIndex: 50,
  },
  invisibleShade: {
    position: 'absolute',
    height: 2000,
    width: 2000,
    left: -500,
    right: 0,
    top: -500,
    zIndex: 49,
    backgroundColor: 'rgba(0,0,0,0)',
  },
  moodMeter: {
    top: 0,
    alignItems: 'center',
    transform: [{ translateY: -230 }],
    justifyContent: 'space-evenly',
    backgroundColor: '#F8FAFC',
    height: theme.sizes.moodMeterHeight,
    width: '99%',
    elevation: 1,
  },
});
