import { StyleSheet, Dimensions } from 'react-native';
import { Theme } from '../theme/theme';

const { width } = Dimensions.get('window');
const isWide = width >= 900;
const calendarWidth = isWide ? 420 : width;
const cellWidth = (calendarWidth - 130) / 7;

const getCardStyle = (theme: Theme) => ({
  backgroundColor: theme.colors.surface,
  borderRadius: theme.radius.xl,
  borderWidth: 1,
  borderColor: theme.colors.border.light,
  shadowColor: '#0F172A',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.04,
  shadowRadius: 8,
  elevation: 2,
});

export const getStyles = (theme) => {
  const CARD_STYLE = getCardStyle(theme);
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: 'transparent',
      paddingHorizontal: 0,
      paddingTop: theme.spacing.smd,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: theme.spacing.xl,
      paddingHorizontal: theme.spacing.xl,
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.border.light,
      paddingVertical: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
      borderRadius: theme.radius.md,
      marginRight: theme.spacing.smd,
    },
    backButtonText: {
      color: theme.colors.text.primary,
      fontSize: 14,
      fontWeight: '600',
      marginLeft: theme.spacing.xs,
    },
    titleText: {
      fontSize: 24,
      fontWeight: 'bold',
      color: theme.colors.text.primary,
    },

    dashboardContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'flex-start',
      width: '100%',
      paddingHorizontal: theme.spacing.xl,
    },
    centralDateBlock: {
      ...CARD_STYLE,
      backgroundColor: theme.colors.icon.bg,
      borderWidth: 0,
      alignItems: 'stretch',
      justifyContent: 'center',
      marginVertical: theme.spacing.smd,
      padding: theme.spacing.xl,
      width: '100%',
    },
    dateButton: {
      width: 116,
      height: 116,
      borderRadius: theme.radius.xl,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 4,
      borderWidth: 3.5,
      borderColor: theme.colors.primary,
    },
    dateNumber: {
      fontSize: 42,
      fontWeight: '900',
    },
    dateMonth: {
      fontSize: 15,
      fontWeight: 'bold',
      textTransform: 'uppercase',
      marginTop: theme.spacing.xs / 2,
    },
    statsRow: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      width: '100%',
      paddingTop: theme.spacing.smd,
      borderTopWidth: 1,
      borderTopColor: 'rgba(59, 130, 246, 0.15)',
    },
    statItem: {
      alignItems: 'center',
    },
    statValue: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.colors.primary,
    },
    statLabel: {
      fontSize: 12,
      color: theme.colors.text.secondary,
      marginTop: theme.spacing.xs,
    },
    gridContainer: {
      width: '100%',
      flexDirection: 'column',
      gap: theme.spacing.lg,
      marginTop: theme.spacing.smd,
      flex: 1,
      marginBottom: theme.spacing.xl,
    },
    menuCard: {
      ...CARD_STYLE,
      backgroundColor: theme.colors.icon.bg,
      borderWidth: 2,
      borderColor: theme.colors.icon.primary,
      flexDirection: 'row',
      alignItems: 'center',
      padding: theme.spacing.xxxl,
      flex: 1,
    },
    menuIconContainer: {
      width: 50,
      height: 50,
      borderRadius: theme.radius.lg,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: theme.spacing.lg,
    },
    menuTextContainer: {
      flex: 1,
    },
    menuTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.colors.text.primary,
    },
    menuSubtitle: {
      fontSize: 12,
      color: theme.colors.text.secondary,
      marginTop: theme.spacing.xs,
    },

    modalContainer: {
      flex: 1,
      backgroundColor: 'rgba(15, 23, 42, 0.4)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: theme.spacing.xl,
    },
    modalContent: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.xl,
      width: '100%',
      maxWidth: 420,
      padding: theme.spacing.xl,
      borderWidth: 1,
      borderColor: theme.colors.border.light,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 10,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: theme.spacing.md,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: theme.colors.text.primary,
    },
    calendarGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      justifyContent: 'flex-start',
      marginBottom: theme.spacing.xl,
    },
    calendarCell: {
      width: cellWidth,
      height: cellWidth,
      borderRadius: theme.radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.border.light,
    },
    calendarCellText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.text.secondary,
    },
    calendarCellTextActive: {
      color: '#FFFFFF',
      fontWeight: 'bold',
    },
    dayDetailBlock: {
      backgroundColor: theme.colors.background,
      borderRadius: theme.radius.xl,
      padding: theme.spacing.lg,
      borderWidth: 1,
      borderColor: theme.colors.border.light,
    },
    dayDetailTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.colors.text.primary,
      marginBottom: theme.spacing.smd,
      textAlign: 'center',
    },
    dayDetailGrid: {
      flexDirection: 'row',
      justifyContent: 'space-around',
    },
    dayDetailItem: {
      alignItems: 'center',
    },
    dayDetailValue: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.colors.text.primary,
      marginTop: theme.spacing.xs,
    },

    inputBlock: {
      flexDirection: 'row',
      paddingBottom: theme.spacing.xl,
      borderBottomWidth: 1,
      borderColor: theme.colors.border.light,
      gap: theme.spacing.smd,
      paddingHorizontal: theme.spacing.xl,
    },
    input: {
      flex: 1,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.lg,
      paddingVertical: theme.spacing.md,
      paddingHorizontal: theme.spacing.lg,
      color: theme.colors.text.primary,
      fontSize: 16,
      elevation: 2,
    },
    typeToggleButtonCompact: {
      width: 44,
      height: 44,
      borderRadius: theme.radius.md,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
    },
    addButton: {
      backgroundColor: theme.colors.primaryLight,
      borderRadius: theme.radius.lg,
      width: 50,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 3,
    },
    habitList: {
      paddingTop: theme.spacing.sm,
      paddingBottom: theme.spacing.lg,
    },
    habitItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.xl,
      elevation: 1,
      overflow: 'hidden',
      position: 'relative',
    },
    habitText: {
      flex: 1,
      fontSize: 16,
      color: theme.colors.text.primary,
      fontWeight: '500',
      marginLeft: theme.spacing.lg,
      marginVertical: theme.spacing.lg,
    },
    habitCount: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.colors.text.secondary,
      marginRight: theme.spacing.lg,
    },
    habitIncrementBtn: {
      padding: theme.spacing.sm,
      borderRadius: theme.spacing.sm,
      backgroundColor: theme.colors.background,
    },

    piggyCard: {
      ...CARD_STYLE,
      backgroundColor: theme.colors.surface,
      padding: theme.spacing.xl,
      marginBottom: theme.spacing.xl,
    },
    piggyInputRowContainer: {
      flexDirection: 'row',
      gap: theme.spacing.md,
      paddingBottom: theme.spacing.xl,
      borderBottomWidth: 1,
      borderColor: theme.colors.border.light,
      alignItems: 'stretch',
      paddingHorizontal: theme.spacing.xl,
    },
    piggyCreateRightButton: {
      width: 120,
      borderRadius: theme.radius.xl,
      backgroundColor: theme.colors.primaryLight,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 2,
    },
    piggyCreateRightButtonText: {
      color: theme.colors.primary,
      fontSize: 17,
      fontWeight: 'bold',
      textAlign: 'center',
      lineHeight: 20,
    },
    piggyInputColumn: {
      flex: 1,
      flexDirection: 'column',
      gap: theme.spacing.smd,
    },
    quickAddRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
    },
    quickAddBtn: {
      flex: 1,
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.radius.sm,
      backgroundColor: theme.colors.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quickAddText: {
      color: theme.colors.text.primary,
      fontWeight: '600',
      fontSize: 12,
    },

    showCard: {
      backgroundColor: 'transparent',
      borderWidth: 0,
      padding: 0,
      overflow: 'visible',
    },
    showTitleBlock: {
      ...CARD_STYLE,
      borderWidth: 0,
      paddingHorizontal: theme.spacing.lg,
      paddingVertical: theme.spacing.mdl,
      marginBottom: 0,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      zIndex: 1,
    },
    showTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.colors.icon.primary,
      textAlign: 'center',
    },
    showControlsRow: {
      flexDirection: 'row',
      width: '100%',
      height: 48,
      alignItems: 'stretch',
      backgroundColor: 'transparent',
      gap: theme.spacing.md,
    },
    showControlGroupLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'stretch',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.icon.bg,
      borderBottomLeftRadius: theme.radius.xl,
      borderBottomRightRadius: theme.radius.xl,
      borderTopLeftRadius: 0,
      borderTopRightRadius: 0,
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 4,
    },
    showControlGroupRight: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'stretch',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.icon.bg,
      borderBottomRightRadius: theme.radius.xl,
      borderBottomLeftRadius: theme.radius.xl,
      borderTopLeftRadius: 0,
      borderTopRightRadius: 0,
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 4,
    },
    showControlLabel: {
      color: theme.colors.text.secondary,
      fontSize: 9,
      fontWeight: 'bold',
      textTransform: 'uppercase',
    },
    showControlValue: {
      color: theme.colors.text.primary,
      fontSize: 16,
      fontWeight: 'bold',
      minWidth: 14,
      textAlign: 'center',
    },
    showControlBtn: {
      width: 48,
      backgroundColor: theme.colors.icon.bg,
      borderWidth: 2,
      borderColor: theme.colors.icon.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    showControlBtnLeft: {
      borderBottomLeftRadius: theme.radius.xl,
    },
    showControlBtnRight: {
      borderBottomRightRadius: theme.radius.xl,
    },
    showControlBtnCenterLeft: {
      borderBottomRightRadius: theme.radius.xl,
    },
    showControlBtnCenterRight: {
      borderBottomLeftRadius: theme.radius.xl,
    },
    movieBadge: {
      backgroundColor: '#6366F1',
      paddingVertical: theme.spacing.xs,
      paddingHorizontal: theme.spacing.mdl,
      borderRadius: theme.radius.lg,
      alignSelf: 'flex-start',
    },
    movieBadgeText: {
      color: '#FFFFFF',
      fontWeight: 'bold',
      fontSize: 12,
    },

    keyboardSuggestionBar: {
      position: 'absolute',
      left: 0,
      right: 0,
      backgroundColor: theme.colors.surface,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: theme.spacing.md,
      paddingHorizontal: theme.spacing.lg,
      borderTopWidth: 1,
      borderColor: theme.colors.border.light,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 10,
      zIndex: 99,
    },
    keyboardSuggestionText: {
      color: theme.colors.text.primary,
      fontWeight: '600',
      fontSize: 16,
    },
    keyboardSuggestionCheckbox: {
      width: 24,
      height: 24,
      borderRadius: theme.radius.sm,
      borderWidth: 2,
      borderColor: theme.colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
    },
    keyboardSuggestionCheckboxChecked: {
      backgroundColor: theme.colors.primary,
    },
    dashboardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
    },
    dashboardStatsColumn: {
      flex: 1,
      flexDirection: 'column',
      justifyContent: 'center',
      gap: theme.spacing.lg,
      marginLeft: theme.spacing.smd,
    },
    statItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    statHabitsValueContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: 6,
    },
    addButtonLarge: {
      height: 44,
      paddingHorizontal: theme.spacing.xl,
      borderRadius: theme.radius.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primaryLight,
      elevation: 1,
    },
    piggyCardCompact: {
      ...CARD_STYLE,
      borderWidth: 0,
      backgroundColor: theme.colors.surface,
      padding: 0,
      overflow: 'hidden',
      borderRadius: theme.radius.xl,
    },
    piggyCardHeader: {
      backgroundColor: theme.colors.icon.bg,
      paddingTop: theme.spacing.smd,
      paddingBottom: theme.spacing.md,
      paddingHorizontal: theme.spacing.xl,
      borderBottomWidth: 1,
      borderColor: 'rgba(59, 130, 246, 0.1)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    piggyCardProgressBarTrack: {
      height: 12,
      backgroundColor: theme.colors.background,
      width: '100%',
      borderRadius: theme.radius.sm,
      overflow: 'hidden',
      marginTop: theme.spacing.sm,
    },
    piggyCardProgressBarFill: {
      height: '100%',
      backgroundColor: theme.colors.primary,
      borderRadius: theme.radius.sm,
    },
    piggyRowOne: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 0,
      height: 56,
    },
    piggyLeftColumnCompact: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      alignSelf: 'stretch',
    },
    piggyCenterColumnCompact: {
      width: 100,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'stretch',
    },
    piggyRightColumnCompact: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'stretch',
    },
    piggyCurrentTextCompact: {
      fontSize: 18,
      color: theme.colors.text.secondary,
      textAlign: 'center',
      fontWeight: 'bold',
    },
    piggyCurrentContainerCompact: {
      width: '100%',
      height: '100%',
      backgroundColor: theme.colors.surface,
      borderWidth: 4,
      borderRightWidth: 0,
      borderColor: theme.colors.icon.bg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    piggyCurrentContainerCompactCompleted: {
      backgroundColor: theme.colors.icon.bg,
    },
    piggyTargetBadge: {
      width: '100%',
      height: '100%',
      backgroundColor: theme.colors.icon.bg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    piggyVerticalDivider: {
      position: 'absolute',
      right: 0,
      top: 0,
      bottom: -2,
      width: 1,
      backgroundColor: 'rgba(59, 130, 246, 0.1)',
    },
    piggyTargetTextCompact: {
      fontSize: 18,
      color: theme.colors.icon.primary,
      textAlign: 'center',
      fontWeight: 'bold',
      fontStyle: 'italic',
    },
    piggyTitleText: {
      fontSize: 18,
      fontWeight: 'bold',
      fontStyle: 'italic',
      color: theme.colors.icon.primary,
      textAlign: 'center',
    },
    piggyInputCompact: {
      width: '100%',
      height: '100%',
      backgroundColor: theme.colors.surface,
      borderWidth: 4,
      borderColor: theme.colors.icon.bg,
      borderTopRightRadius: 0,
      borderBottomRightRadius: theme.radius.xl,
      borderTopLeftRadius: 0,
      borderBottomLeftRadius: 0,
      paddingHorizontal: theme.spacing.xs / 2,
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.colors.icon.primary,
      textAlign: 'center',
      paddingVertical: 0,
    },
    piggyInputCompactFocused: {
      backgroundColor: theme.colors.primary + '0F',
      borderColor: theme.colors.icon.primary,
      borderWidth: 4,
    },
    piggyInputCoinsPlaceholder: {
      position: 'absolute',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    piggyFloatingContainer: {
      position: 'absolute',
      left: 0,
      right: 0,
      height: 52,
      backgroundColor: theme.colors.surface,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      paddingHorizontal: theme.spacing.xl,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border.light,
      gap: theme.spacing.lg,
      elevation: 10,
      zIndex: 99,
    },
    piggyFloatingBtn: {
      flex: 1,
      height: 38,
      borderRadius: theme.radius.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      gap: theme.spacing.xs,
    },
    piggyFloatingBtnText: {
      fontSize: 14,
      fontWeight: 'bold',
    },
  });
};
